name: bubbles
channels:
  - defaults
  - conda-forge
dependencies:
  - python
  - fiona
  - rtree
  - requests
  - matplotlib
  - pyproj
  - jupyterlab
  - pandas
  - numpy
  - shapely
  - ipykernel
  - notebook
